# This file was generated by GoReleaser. DO NOT EDIT.
cask "bem" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "4a0278b6f0d35ef14c283ea859626ce1b7c5fdf54aa9bb7c574bdd4f69c1086e"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "c553862e94b09e34db36e29d92760d01ff94f09cfb88503d01b17a06b8979b18"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "33cda07dc4db2a217871e25b1b9fb8456dcad4be60b7287a70236cf78f9770c1"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb13968e160dad27407fb5a277706f23f62a5a2afcbab6dc68c5c86c3a4d37d9"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bem"
  desc "The official CLI for bem."
  homepage "https://bem.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bem"
  manpage "man/man1/bem.1.gz"
  bash_completion "completions/bem.bash"
  fish_completion "completions/bem.fish"
  zsh_completion "completions/bem.zsh"

  # No zap stanza required

end
