# This file was generated by GoReleaser. DO NOT EDIT.
cask "bem" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "af472c51a91fde499c664bc2e30138c9032b323943961983c0f79d4cf43de0b0"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "715c07dff412c9f16ca9d0952625383ffb6c1c7009a05e82ad2000cf46428dd2"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1c07ba2bac018485addae48c0cdb6f2ff890709a4242eac798bbe46f98d4839"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d415ab6381790c82f86160257388de7bd890864faf09ab8c6adba93ba48d92c2"
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bem"
  desc "The official CLI for bem."
  homepage "https://bem.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bem"
  manpage "man/man1/bem.1.gz"
  bash_completion "completions/bem.bash"
  fish_completion "completions/bem.fish"
  zsh_completion "completions/bem.zsh"

  # No zap stanza required

end
