# This file was generated by GoReleaser. DO NOT EDIT.
cask "bem" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_amd64.zip"
      sha256 "c08890cdd973bc14dbf471d49148d5484bdba47527357ecc7c107459207e94d9"
    end
    on_arm do
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_macos_arm64.zip"
      sha256 "63b06503b07cf366f72f8869881c3354b46d1bd0d6ee72ebbafa3af0c0b54acf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_amd64.tar.gz"
      sha256 "a03d57f926c7433f06cea07584e3bb1e121b84d1dad7d5a3b0e94a6f7c75a360"
    end
    on_arm do
      url "https://github.com/bem-team/bem-cli/releases/download/v#{version}/bem_#{version}_linux_arm64.tar.gz"
      sha256 "ec1778509011c4e312d67dd4719854e93ad96e7a5bf015e6a40a48b22f8d0519"
    end
  end

  name "bem"
  desc "The official CLI for bem."
  homepage "https://bem.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bem"
  manpage "man/man1/bem.1.gz"
  bash_completion "completions/bem.bash"
  fish_completion "completions/bem.fish"
  zsh_completion "completions/bem.zsh"

  # No zap stanza required

end
